{% set name = "ShortCut" %}
{% set version = "1.0" %}
{% set sha256 = "66e2f45e1ae8cda98590757fcdb06e2d6603f241869a0ee3cb8a49846921df11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Aez35/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('shortcut', max_pin="x") }}

requirements:
  run:
    - python >=3.6
    - biopython >=1.85
    - r-base >=4.3.3
    - r-tidyverse >=2.0
    - r-ggplot2 >=3.5.2
    - shortstack >=4.0.4
    - cutadapt >=4.8
    - rpy2 >=25.3.1
    - cutadapt >=4.8


test:
  commands:
    - ShortCut --help

about:
  home: https://github.com/Aez35/ShortCut
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ShortCut Small RNA-seq data trimmer and quality control tool'
